//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexGenMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditIntervention
    {
        public string auditId { get; set; }
        public string interventionId { get; set; }
        public System.DateTime auditDate { get; set; }
        public int interventionLife { get; set; }
        public string interventionComment { get; set; }
        public string userId { get; set; }
    
        public virtual Intervention Intervention { get; set; }
        public virtual User User { get; set; }
    }
}
