//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexGenMVC.Models
{
    using System;
    
    public partial class Fn_GetDefaultIntervention_Result1
    {
        public string interventionName { get; set; }
        public double interventionDefaultCost { get; set; }
        public double interventionDefaultHours { get; set; }
    }
}
