//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexGenMVC.Models
{
    using System;
    
    public partial class Fn_GetInterventionForEdit_Result1
    {
        public string interventionId { get; set; }
        public string clientID { get; set; }
        public double interventionCost { get; set; }
        public System.DateTime interventionDate { get; set; }
        public string interventionTypeName { get; set; }
        public string status { get; set; }
    }
}
