//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexGenMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DefaultConnectionEntities : DbContext
    {
        public DefaultConnectionEntities()
            : base("name=DefaultConnectionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AuditIntervention> AuditInterventions { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<DefaultIntervention> DefaultInterventions { get; set; }
        public virtual DbSet<Intervention> Interventions { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<GetClient_Result> GetClient(string userid, Nullable<int> opt, string clientId, string clientName, string clientDesLoc)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("Userid", userid) :
                new ObjectParameter("Userid", typeof(string));
    
            var optParameter = opt.HasValue ?
                new ObjectParameter("opt", opt) :
                new ObjectParameter("opt", typeof(int));
    
            var clientIdParameter = clientId != null ?
                new ObjectParameter("clientId", clientId) :
                new ObjectParameter("clientId", typeof(string));
    
            var clientNameParameter = clientName != null ?
                new ObjectParameter("clientName", clientName) :
                new ObjectParameter("clientName", typeof(string));
    
            var clientDesLocParameter = clientDesLoc != null ?
                new ObjectParameter("clientDesLoc", clientDesLoc) :
                new ObjectParameter("clientDesLoc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetClient_Result>("GetClient", useridParameter, optParameter, clientIdParameter, clientNameParameter, clientDesLocParameter);
        }
    
        public virtual ObjectResult<Fn_GetClint_Result> Fn_GetClient(string userid, Nullable<int> opt, string clientId, string clientName, string clientDesLoc)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("Userid", userid) :
                new ObjectParameter("Userid", typeof(string));
    
            var optParameter = opt.HasValue ?
                new ObjectParameter("opt", opt) :
                new ObjectParameter("opt", typeof(int));
    
            var clientIdParameter = clientId != null ?
                new ObjectParameter("clientId", clientId) :
                new ObjectParameter("clientId", typeof(string));
    
            var clientNameParameter = clientName != null ?
                new ObjectParameter("clientName", clientName) :
                new ObjectParameter("clientName", typeof(string));
    
            var clientDesLocParameter = clientDesLoc != null ?
                new ObjectParameter("clientDesLoc", clientDesLoc) :
                new ObjectParameter("clientDesLoc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Fn_GetClint_Result>("Fn_GetClient", useridParameter, optParameter, clientIdParameter, clientNameParameter, clientDesLocParameter);
        }
    
        public virtual ObjectResult<string> Fn_GetClientId(string userid, Nullable<int> opt, string clientId, string clientName, string clientDesLoc)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("Userid", userid) :
                new ObjectParameter("Userid", typeof(string));
    
            var optParameter = opt.HasValue ?
                new ObjectParameter("opt", opt) :
                new ObjectParameter("opt", typeof(int));
    
            var clientIdParameter = clientId != null ?
                new ObjectParameter("clientId", clientId) :
                new ObjectParameter("clientId", typeof(string));
    
            var clientNameParameter = clientName != null ?
                new ObjectParameter("clientName", clientName) :
                new ObjectParameter("clientName", typeof(string));
    
            var clientDesLocParameter = clientDesLoc != null ?
                new ObjectParameter("clientDesLoc", clientDesLoc) :
                new ObjectParameter("clientDesLoc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Fn_GetClientId", useridParameter, optParameter, clientIdParameter, clientNameParameter, clientDesLocParameter);
        }
    
        public virtual int Fn_InsertClient(string userid, Nullable<int> opt, string clientId, string clientName, string clientDesLoc)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("Userid", userid) :
                new ObjectParameter("Userid", typeof(string));
    
            var optParameter = opt.HasValue ?
                new ObjectParameter("opt", opt) :
                new ObjectParameter("opt", typeof(int));
    
            var clientIdParameter = clientId != null ?
                new ObjectParameter("clientId", clientId) :
                new ObjectParameter("clientId", typeof(string));
    
            var clientNameParameter = clientName != null ?
                new ObjectParameter("clientName", clientName) :
                new ObjectParameter("clientName", typeof(string));
    
            var clientDesLocParameter = clientDesLoc != null ?
                new ObjectParameter("clientDesLoc", clientDesLoc) :
                new ObjectParameter("clientDesLoc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Fn_InsertClient", useridParameter, optParameter, clientIdParameter, clientNameParameter, clientDesLocParameter);
        }
    
        public virtual ObjectResult<GetInterventions_Result> GetInterventions(string userId)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInterventions_Result>("GetInterventions", userIdParameter);
        }
    
        public virtual ObjectResult<InsertIntervenion_Result> InsertIntervenion(string interventionId, string clientId, string userId, Nullable<double> interventionHours, Nullable<double> interventionCosts, string status, string interventionTypeName)
        {
            var interventionIdParameter = interventionId != null ?
                new ObjectParameter("InterventionId", interventionId) :
                new ObjectParameter("InterventionId", typeof(string));
    
            var clientIdParameter = clientId != null ?
                new ObjectParameter("ClientId", clientId) :
                new ObjectParameter("ClientId", typeof(string));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            var interventionHoursParameter = interventionHours.HasValue ?
                new ObjectParameter("InterventionHours", interventionHours) :
                new ObjectParameter("InterventionHours", typeof(double));
    
            var interventionCostsParameter = interventionCosts.HasValue ?
                new ObjectParameter("InterventionCosts", interventionCosts) :
                new ObjectParameter("InterventionCosts", typeof(double));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var interventionTypeNameParameter = interventionTypeName != null ?
                new ObjectParameter("InterventionTypeName", interventionTypeName) :
                new ObjectParameter("InterventionTypeName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InsertIntervenion_Result>("InsertIntervenion", interventionIdParameter, clientIdParameter, userIdParameter, interventionHoursParameter, interventionCostsParameter, statusParameter, interventionTypeNameParameter);
        }
    
        public virtual ObjectResult<Fn_GetIntervention_Result1> Fn_GetIntervention(string userId)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Fn_GetIntervention_Result1>("Fn_GetIntervention", userIdParameter);
        }
    
        public virtual int Fn_InsertIntervention(string interventionId, string clientId, string userId, Nullable<double> interventionHours, Nullable<double> interventionCosts, string status, string interventionTypeName)
        {
            var interventionIdParameter = interventionId != null ?
                new ObjectParameter("InterventionId", interventionId) :
                new ObjectParameter("InterventionId", typeof(string));
    
            var clientIdParameter = clientId != null ?
                new ObjectParameter("ClientId", clientId) :
                new ObjectParameter("ClientId", typeof(string));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            var interventionHoursParameter = interventionHours.HasValue ?
                new ObjectParameter("InterventionHours", interventionHours) :
                new ObjectParameter("InterventionHours", typeof(double));
    
            var interventionCostsParameter = interventionCosts.HasValue ?
                new ObjectParameter("InterventionCosts", interventionCosts) :
                new ObjectParameter("InterventionCosts", typeof(double));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var interventionTypeNameParameter = interventionTypeName != null ?
                new ObjectParameter("InterventionTypeName", interventionTypeName) :
                new ObjectParameter("InterventionTypeName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Fn_InsertIntervention", interventionIdParameter, clientIdParameter, userIdParameter, interventionHoursParameter, interventionCostsParameter, statusParameter, interventionTypeNameParameter);
        }
    
        public virtual ObjectResult<GetDefaultIntervention_Result> GetDefaultIntervention()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDefaultIntervention_Result>("GetDefaultIntervention");
        }
    
        public virtual ObjectResult<Fn_GetDefaultIntervention_Result1> Fn_GetDefaultIntervention()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Fn_GetDefaultIntervention_Result1>("Fn_GetDefaultIntervention");
        }
    
        public virtual ObjectResult<GetDefaultCostHour_Result> GetDefaultCostHour(string userId)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDefaultCostHour_Result>("GetDefaultCostHour", userIdParameter);
        }
    
        public virtual ObjectResult<Fn_GetDefaultCostHour_Result> Fn_GetDefaultCostHour(string userId)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Fn_GetDefaultCostHour_Result>("Fn_GetDefaultCostHour", userIdParameter);
        }
    
        public virtual ObjectResult<string> GetIngterventionId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetIngterventionId");
        }
    
        public virtual ObjectResult<string> GetInterventionId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetInterventionId");
        }
    
        public virtual ObjectResult<string> Fn_GetInterventionId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Fn_GetInterventionId");
        }
    
        public virtual ObjectResult<string> GetAuditId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetAuditId");
        }
    
        public virtual ObjectResult<GetAuditIntervention_Result> GetAuditIntervention(string userId)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAuditIntervention_Result>("GetAuditIntervention", userIdParameter);
        }
    
        public virtual int InsertAudit(string auditId, string interventionId, Nullable<int> interventionLife, string interventionComment, string userId)
        {
            var auditIdParameter = auditId != null ?
                new ObjectParameter("AuditId", auditId) :
                new ObjectParameter("AuditId", typeof(string));
    
            var interventionIdParameter = interventionId != null ?
                new ObjectParameter("InterventionId", interventionId) :
                new ObjectParameter("InterventionId", typeof(string));
    
            var interventionLifeParameter = interventionLife.HasValue ?
                new ObjectParameter("InterventionLife", interventionLife) :
                new ObjectParameter("InterventionLife", typeof(int));
    
            var interventionCommentParameter = interventionComment != null ?
                new ObjectParameter("InterventionComment", interventionComment) :
                new ObjectParameter("InterventionComment", typeof(string));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertAudit", auditIdParameter, interventionIdParameter, interventionLifeParameter, interventionCommentParameter, userIdParameter);
        }
    
        public virtual ObjectResult<string> Fn_GetAuditId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Fn_GetAuditId");
        }
    
        public virtual ObjectResult<Fn_GetAuditIntervention_Result> Fn_GetAuditIntervention(string userId)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Fn_GetAuditIntervention_Result>("Fn_GetAuditIntervention", userIdParameter);
        }
    
        public virtual int Fn_InsertAuditIntervention(string auditId, string interventionId, Nullable<int> interventionLife, string interventionComment, string userId)
        {
            var auditIdParameter = auditId != null ?
                new ObjectParameter("AuditId", auditId) :
                new ObjectParameter("AuditId", typeof(string));
    
            var interventionIdParameter = interventionId != null ?
                new ObjectParameter("InterventionId", interventionId) :
                new ObjectParameter("InterventionId", typeof(string));
    
            var interventionLifeParameter = interventionLife.HasValue ?
                new ObjectParameter("InterventionLife", interventionLife) :
                new ObjectParameter("InterventionLife", typeof(int));
    
            var interventionCommentParameter = interventionComment != null ?
                new ObjectParameter("InterventionComment", interventionComment) :
                new ObjectParameter("InterventionComment", typeof(string));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Fn_InsertAuditIntervention", auditIdParameter, interventionIdParameter, interventionLifeParameter, interventionCommentParameter, userIdParameter);
        }
    
        public virtual ObjectResult<GetInterventionForEdit_Result> GetInterventionForEdit(string interventionId)
        {
            var interventionIdParameter = interventionId != null ?
                new ObjectParameter("InterventionId", interventionId) :
                new ObjectParameter("InterventionId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInterventionForEdit_Result>("GetInterventionForEdit", interventionIdParameter);
        }
    
        public virtual ObjectResult<Fn_GetInterventionForEdit_Result3> Fn_GetInterventionForEdit(string interventionId)
        {
            var interventionIdParameter = interventionId != null ?
                new ObjectParameter("InterventionId", interventionId) :
                new ObjectParameter("InterventionId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Fn_GetInterventionForEdit_Result3>("Fn_GetInterventionForEdit", interventionIdParameter);
        }
    
        public virtual int EditInterventionSE(string interventionStatus, string interventionId, Nullable<int> opt, string userId)
        {
            var interventionStatusParameter = interventionStatus != null ?
                new ObjectParameter("InterventionStatus", interventionStatus) :
                new ObjectParameter("InterventionStatus", typeof(string));
    
            var interventionIdParameter = interventionId != null ?
                new ObjectParameter("InterventionId", interventionId) :
                new ObjectParameter("InterventionId", typeof(string));
    
            var optParameter = opt.HasValue ?
                new ObjectParameter("Opt", opt) :
                new ObjectParameter("Opt", typeof(int));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EditInterventionSE", interventionStatusParameter, interventionIdParameter, optParameter, userIdParameter);
        }
    
        public virtual ObjectResult<string> Procedure(string uid)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Procedure", uidParameter);
        }
    
        public virtual int Fn_EditInterventionSE(string interventionStatus, string interventionId, Nullable<int> opt, string userId)
        {
            var interventionStatusParameter = interventionStatus != null ?
                new ObjectParameter("InterventionStatus", interventionStatus) :
                new ObjectParameter("InterventionStatus", typeof(string));
    
            var interventionIdParameter = interventionId != null ?
                new ObjectParameter("InterventionId", interventionId) :
                new ObjectParameter("InterventionId", typeof(string));
    
            var optParameter = opt.HasValue ?
                new ObjectParameter("Opt", opt) :
                new ObjectParameter("Opt", typeof(int));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Fn_EditInterventionSE", interventionStatusParameter, interventionIdParameter, optParameter, userIdParameter);
        }
    
        public virtual ObjectResult<GetInterventionForManager_Result> GetInterventionForManager(string userId)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInterventionForManager_Result>("GetInterventionForManager", userIdParameter);
        }
    
        public virtual ObjectResult<GetInterventionProposedForManager_Result> GetInterventionProposedForManager(string userId)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInterventionProposedForManager_Result>("GetInterventionProposedForManager", userIdParameter);
        }
    
        public virtual ObjectResult<Fn_GetProposedInterventions_Result> Fn_GetProposedInterventions(string userId)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Fn_GetProposedInterventions_Result>("Fn_GetProposedInterventions", userIdParameter);
        }
    
        public virtual ObjectResult<Fn_GetInterventionForManager_Result> Fn_GetInterventionForManager(string userId)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Fn_GetInterventionForManager_Result>("Fn_GetInterventionForManager", userIdParameter);
        }
    
        public virtual ObjectResult<Reports_Result> Reports(Nullable<int> opt, string district)
        {
            var optParameter = opt.HasValue ?
                new ObjectParameter("Opt", opt) :
                new ObjectParameter("Opt", typeof(int));
    
            var districtParameter = district != null ?
                new ObjectParameter("District", district) :
                new ObjectParameter("District", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Reports_Result>("Reports", optParameter, districtParameter);
        }
    
        public virtual ObjectResult<Fn_Report_Result> Fn_Report(Nullable<int> opt, string district)
        {
            var optParameter = opt.HasValue ?
                new ObjectParameter("Opt", opt) :
                new ObjectParameter("Opt", typeof(int));
    
            var districtParameter = district != null ?
                new ObjectParameter("District", district) :
                new ObjectParameter("District", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Fn_Report_Result>("Fn_Report", optParameter, districtParameter);
        }
    }
}
