//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexGenMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIntervention
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblIntervention()
        {
            this.tblAuditInterventions = new HashSet<tblAuditIntervention>();
        }
    
        public string interventionId { get; set; }
        public string clientID { get; set; }
        public string userID { get; set; }
        public string managerId { get; set; }
        public double interventionHours { get; set; }
        public double interventionCost { get; set; }
        public string status { get; set; }
        public System.DateTime interventionDate { get; set; }
        public string interventionTypeName { get; set; }
        public string district { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAuditIntervention> tblAuditInterventions { get; set; }
        public virtual tblClient tblClient { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
